services:
  backend:
    build: .
    container_name: pesona-backend
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: 127.0.0.1
      PORT: 3010
    network_mode: host
    restart: always
    volumes:
      - ./backend/uploads:/app/uploads
